# Generated by Django 4.2.7 on 2023-12-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meseros',
            old_name='nacionalidad',
            new_name='pais',
        ),
    ]
